# Generated by Django 2.2.9 on 2020-01-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment_post_profile_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
    ]
