# Generated by Django 2.2.9 on 2020-01-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_is_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
